version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    command: >
      bash -c 'python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:3000'
    volumes:
      - .:/code
    ports:
      - '3000:3000'
    depends_on:
      - db
